### ISSUE TITLE
Using OBS in workflow

### ISSUE THREAD

**Issue by otsegun** [xiaoxiae/videos#12]
Hi, 
Thanks a lot for the awesome videos you've put out. I wanted to ask some questions about your workflow document. 

I understand that you render the videos using the `build` and this generates the video for each scene, together with a folder for each scene and their renamed partial movie files. 

1. My main question is how you use OBS in your workflow after this rendering step. This is not exactly clear to me and I was thinking at first that maybe you use it to record your voice over the videos (by recording the screen and voice OBS while playing the rendered scenes). But then it seems to me that you do the recording separately using the arecord and then add those over the rendered Scenes in kdenlive. 

I'd appreciate if you can explain a little bit how you use OBS in your workflow and also shed some light on the voice recording process. 

I am looking to make some videos and I am testing to see if I can adopt some of your workflow. 

Apologies if this is not the right place to ask this sort of questions but I wasn't sure on how to consult you with this question. 

Thanks.

**Comment by xiaoxiae** [comment]
Hey,
thanks for the kind words!

You're right, I don't use OBS for recording audio, only for recording my screen.

For voice, I use the scripts in `<video folder>/audio/raw`. What I usually do is
1. run `./get_noise_profile` and stay silent so the microphone noise is sampled
2. run `./record <name>` to record a specific paragraph / whatever (with the noise filtered out)
3. run `<video folder>/normalize` to normalize the loudness across all of the audio tracks

I'm happy that you're looking to make some videos, looking forward to watching them :).

**Comment by xiaoxiae** [comment]
Oops, the `audio` folder is gitignored. I force-added them for the templates (projects starting with `00-`) so you can look there.

**Comment by otsegun** [comment]
Thanks for the quick reply and for uploading the audio folder.
